# Generated by Django 3.0.7 on 2020-09-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200925_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
