# Generated by Django 3.0.7 on 2020-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200925_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
