# Generated by Django 3.1 on 2020-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layers',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
    ]
